model_list:
  - model_name: gpt-4-turbo-preview
    litellm_params:
      model: gpt-4-turbo-preview
      api_key: ${OPENAI_API_KEY}

  - model_name: grok-2-1212
    litellm_params:
      model: grok-2-1212
      api_key: ${XAI_API_KEY}

  - model_name: claude-3-5-sonnet-20241022
    litellm_params:
      model: claude-3-5-sonnet-20241022
      api_key: ${ANTHROPIC_API_KEY}

  - model_name: gemini-pro
    litellm_params:
      model: google/gemini-pro
      api_key: ${GOOGLE_API_KEY}

environment_variables:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  XAI_API_KEY: ${XAI_API_KEY}
  ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
  GOOGLE_API_KEY: ${GOOGLE_API_KEY}

litellm_settings:
  drop_params: True
  set_verbose: True
  model_list: True