model_list:
  - model_name: deepseek/deepseek-r1
    litellm_params:
      model: deepseek-r1
      api_key: ${OPENROUTER_API_KEY}
      api_base: https://openrouter.ai/api/v1

environment_variables:
  OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}

litellm_settings:
  drop_params: False
  set_verbose: True
  model_list: True